name: test-basics
on:
  push:
    branches:
      - ci-testing
      - main
      - release/* #ToDo: add a release branch
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    needs: platform
    runs-on: ubuntu-latest #ToDo: ${{ needs.build.outputs.os }}
    strategy:
      matrix:
        modules: [01_write_ivy_code, 02_unify_code, 03_compile_code, 04_transpile_code, 05_lazy_vs_eager, 06_how_to_use_decorators, 07_transpile_any_library, 08_transpile_any_model, 09_write_a_model_using_ivy]

    steps:
      - name: Checkout DemosðŸ›Ž
        uses: actions/checkout@v2
        with:
          path: demos
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Run Demo Testing
        id: tests
        run: |
          cd demos
          docker run -v `pwd`:/ivy/demos unifyai/ivy:latest demos/tests/test_demos.sh ${{ secrets.USER_API_KEY }} ${{ matrix.modules }}.ipynb "basics"
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome!= 'success'
        run: exit 1

